---
- hosts: rasp
  become: true
  
  tasks:
  - name: Update apt-get repo and cache
    tags: one, two
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    when: ansible_distribution == "Ubuntu"
  - name: Upgrade all apt packages
    tags: three, four
    apt: upgrade=dist force_apt_get=yes
    when: ansible_distribution == "Ubuntu"
  - name: copy default html file for site
    tags: seven
    copy:
      src: default_site.html
      dest: /home/ubuntu/index1.html
      owner: root
      group: root
      mode: 0644

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: nine
    user:
      name: simone
      groups: root

- hosts: aws, linode
  become: true

  tasks:
  - name: Update apt-get repo and cache
    tags: five, six
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
